# Generated by Django 6.1 on 2026-08-26 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_sprint'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#42526E', help_text='Hex color for the column header', max_length=7)),
                ('category', models.CharField(choices=[('TODO', 'To Do'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done')], default='TODO', max_length=15)),
                ('position', models.PositiveIntegerField(default=0, help_text='Left-to-right order on the board')),
                ('is_default', models.BooleanField(default=False, help_text='Pre-selected status when creating a new issue')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_states', to='projects.project')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='projects.workflowstate')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transitions', to='projects.project')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='projects.workflowstate')),
            ],
            options={
                'unique_together': {('project', 'from_state', 'to_state')},
            },
        ),
    ]
