# Generated by Django 6.1 on 2026-08-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='figma_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='github_pr',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
