# Generated by Django 6.1 on 2026-08-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_issue_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolution',
            field=models.CharField(blank=True, default='Unresolved', max_length=30),
        ),
    ]
